### PR TITLE
Shiftui integration

### PR DESCRIPTION
**Pull request by ComputeLinux**
DO NOT MERGE YET
Just so we can see problems and stuff
Fix things:
- [x] Fix Shiftorium
- [x] Fix Textpad
- [x] Fix Knowledge Input
- [x] Fix window borders
- [x] Fix Pong
- [x] Fix Artpad Cancel
- [x] Fix dialog box text/button pos
- [x] Bug from testing - Weird auto scroll on terminal.
- [x] Bug from testing - Application button is flickery.

Finish things;
- [x] Finish Shifter

Backport things:
- [x] Cheats
- [x] Core utils
- [x] Command functionize
- [x] Terminal tweaks
- [x] Remove beeping

Test things:
- [x] Bugs

### CODE REVIEW

**Comment by carverh** [comment]
We need a leankit board

**Comment by ComputeLinux** [comment]
yea we do

**Comment by carverh** [comment]
Sorry Guys that I Couldn't Work Today... Be Back Tomorrow.

**Comment by carverh** [comment]
Is Everything Ready

**Comment by MichaelTheShifter** [comment]
Got two hours till the last shiftui stream today, just woke up, seems my PC's doing OK so I'll be working on finishing the shifter.

Thanks everyone for helpin' me out with this!

**Comment by carverh** [comment]
i got to merge it so i can edit it

**Comment by MichaelTheShifter** [comment]
Congratulations everybody! We did it. Merged!

**Pull request merged**
